/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import master.petugas;
import master.supplier;
import uniqid.uniqid;
import transaksi.masuk;
import master.stok;
/**
 *
 * @author imam
 */
public class modalTransaksiMasuk extends javax.swing.JDialog {
    supplier supplier;
    uniqid uniqid;
    masuk trMasuk;
    stok stok;
    petugas petugas;
    
    boolean pilih = false;
    String[][] dataBarangMasuk = null;
    String[] dataSession = null;
    /**
     * Creates new form modalTransaksiMasuk
     */
    public modalTransaksiMasuk(java.awt.Frame parent, boolean modal, String[][] data, String[] session) {
        super(parent, modal);
        initComponents();
        supplier = new supplier();
        uniqid = new uniqid();
        trMasuk = new masuk();
        stok = new stok();
        petugas = new petugas();
        
        dataBarangMasuk = data;
        dataSession = session;
        
        // hide
        txtKodeSupplier.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        cbbNamaSupplier = new javax.swing.JComboBox();
        txtKodeSupplier = new javax.swing.JTextField();
        btnTambahTranaksiMasuk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(220, 239, 201));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Pilih Supplier");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 204, 30));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel59.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel59.setText("Nama Supplier  :");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        cbbNamaSupplier.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        cbbNamaSupplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbNamaSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbNamaSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNamaSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(cbbNamaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 220, 30));
        jPanel1.add(txtKodeSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, -1));

        btnTambahTranaksiMasuk.setBackground(new java.awt.Color(0, 102, 102));
        btnTambahTranaksiMasuk.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTambahTranaksiMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahTranaksiMasuk.setText("Pilih");
        btnTambahTranaksiMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahTranaksiMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTranaksiMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahTranaksiMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getCbbNamaSupplier() {
        return cbbNamaSupplier;
    }
    
    private String[] getKodeFromCbb(String[][] data, int cbbSelect){
        String[] value = new String[data[0].length];
        for (int i = 0; i < value.length; i++) {
            value[i] = data[cbbSelect][i];
        }
        return value;
    }
    
    public String tglSekarang(String format){
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat(format);
        String data = s.format(ys);
        return data;
    }
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnTambahTranaksiMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTranaksiMasukActionPerformed
        // TODO add your handling code here:
        String kode_transaksi = uniqid.get();
        String tgl_transaksi = tglSekarang("yyyy-MM-dd hh:mm:ss");
        String kode_supplier = txtKodeSupplier.getText();
        String kode_petugas = dataSession[0];
        int total = 0;
        for (int i = 0; i < dataBarangMasuk.length; i++) {
            int sub_total = Integer.parseInt(dataBarangMasuk[i][2]);
            total += sub_total;
        }
        String total2 = String.valueOf(total);
        String[][] dataTrMasuk = {
            {"kode_transaksi", kode_transaksi},
            {"tgl_transaksi", tgl_transaksi},
            {"kode_supplier", kode_supplier},
            {"kode_petugas", kode_petugas},
            {"total", total2}
        };
        trMasuk.save(dataTrMasuk);
        for (int i = 0; i < dataBarangMasuk.length; i++) {
            String kode_detail = uniqid.get();
            String kode_barang = dataBarangMasuk[i][0];
            String qty = dataBarangMasuk[i][1];
            String sub_total = dataBarangMasuk[i][2];
            String[][] dataDtlTrMasuk = {
                {"kode_detail", kode_detail},
                {"kode_transaksi", kode_transaksi},
                {"kode_barang", kode_barang},
                {"qty", qty},
                {"sub_total", sub_total}
            };
            trMasuk.save_detail(dataDtlTrMasuk);
            
            String[] data_petugas = petugas.get_id(kode_petugas);
            String kode_gudang = data_petugas[5];
            String[] data_stok = stok.getStok(kode_barang, kode_gudang);
            if (data_stok == null) {
                String kode_stok = uniqid.get();
                String[][] data = {
                    {"kode_stok", kode_stok},
                    {"kode_barang", kode_barang},
                    {"stok", qty},
                    {"kode_gudang", kode_gudang}
                };
                stok.save(data);
            }else{
                String kode_stok = data_stok[0];
                int stokAwal = Integer.parseInt(data_stok[2]);
                int stokMasuk = Integer.parseInt(qty);
                int stokSekarang = stokAwal + stokMasuk;
                String[][] data = {
                    {"kode_barang", kode_barang},
                    {"stok", String.valueOf(stokSekarang)},
                    {"kode_gudang", kode_gudang}
                };
                stok.edit(data, kode_stok);
            }
        }
        this.setVisible(false);
        MenuUtama mu = new MenuUtama("transaksi masuk", dataSession);
        mu.hide();
        mu.show();
    }//GEN-LAST:event_btnTambahTranaksiMasukActionPerformed

    private void cbbNamaSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNamaSupplierActionPerformed
        // TODO add your handling code here:
        if (cbbNamaSupplier.getSelectedIndex() > -1) {
            int cbbSelect = cbbNamaSupplier.getSelectedIndex();
            String[][] data_supplier = supplier.get_all();
            String[] data_supplier2 = getKodeFromCbb(data_supplier, cbbSelect);
            txtKodeSupplier.setText(data_supplier2[1]);
        }
    }//GEN-LAST:event_cbbNamaSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(modalTransaksiMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(modalTransaksiMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(modalTransaksiMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(modalTransaksiMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                modalTransaksiMasuk dialog = new modalTransaksiMasuk(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahTranaksiMasuk;
    private javax.swing.JComboBox cbbNamaSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtKodeSupplier;
    // End of variables declaration//GEN-END:variables
}
