/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import master.petugas;
import uniqid.uniqid;
import transaksi.keluar;
import master.stok;
import javax.swing.JOptionPane;
import master.gudang;
/**
 *
 * @author imam
 */
public class modalPilihTransaksiKeluarCabang extends javax.swing.JDialog {

    MenuUtama mu;
    petugas petugas;
    uniqid uniqid;
    keluar keluar;
    stok stok;
    gudang gudang;
    
    String[] session;
    String[][] dataBarang;
    /**
     * Creates new form modalPilihTransaksiKeluarCabang
     */
    public modalPilihTransaksiKeluarCabang(java.awt.Frame parent, boolean modal, String[] session, MenuUtama mu, 
            String[][] databarang) {
        super(parent, modal);
        initComponents();
        this.mu = mu;
        petugas = new petugas();
        uniqid = new uniqid();
        keluar = new keluar();
        stok = new stok();
        gudang = new gudang();
        
        this.session = session;
        String kode_gudang = this.session[5];
        String[][] data = gudang.getAllKecualiLogin(kode_gudang);
        mu.tampilCbb(data, 2, cbbNamaGudang);
        this.dataBarang = databarang;
        
        //hide
        txtKodeGudang.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        cbbNamaGudang = new javax.swing.JComboBox();
        txtKodeGudang = new javax.swing.JTextField();
        btnTambahTranaksiKeluarCabang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(220, 239, 201));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Pilih Cabang");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 204, 30));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel59.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel59.setText("Nama Cabang  :");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        cbbNamaGudang.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        cbbNamaGudang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbNamaGudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbNamaGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNamaGudangActionPerformed(evt);
            }
        });
        jPanel1.add(cbbNamaGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 220, 30));
        jPanel1.add(txtKodeGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, -1));

        btnTambahTranaksiKeluarCabang.setBackground(new java.awt.Color(0, 102, 102));
        btnTambahTranaksiKeluarCabang.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTambahTranaksiKeluarCabang.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahTranaksiKeluarCabang.setText("Pilih");
        btnTambahTranaksiKeluarCabang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahTranaksiKeluarCabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTranaksiKeluarCabangActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahTranaksiKeluarCabang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void cbbNamaGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNamaGudangActionPerformed
        // TODO add your handling code here:
        if (cbbNamaGudang.getSelectedIndex() > -1) {
            int cbbSelect = cbbNamaGudang.getSelectedIndex();
            String kode_gudang = session[5];
            String[][] data_gudang = gudang.getAllKecualiLogin(kode_gudang);
            String[] data_gudang2 = mu.getKodeFromCbb(data_gudang, cbbSelect);
            txtKodeGudang.setText(data_gudang2[1]);
        }
    }//GEN-LAST:event_cbbNamaGudangActionPerformed

    private void btnTambahTranaksiKeluarCabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTranaksiKeluarCabangActionPerformed
        // TODO add your handling code here:
        String kode_transaksi = uniqid.get();
        String tgl_transaksi = mu.tglSekarang("yyyy-MM-dd hh:mm:ss");
        String kode_gudang = txtKodeGudang.getText();
        String kode_petugas = session[0];
        String[][] dataTrKeluar = {
            {"kode_transaksi", kode_transaksi},
            {"tgl_transaksi", tgl_transaksi},
            {"kode_gudang", kode_gudang},
            {"kode_petugas", kode_petugas},
            {"konfirmasi_cabang", "Belum"}
        };
        keluar.save(dataTrKeluar);
        for (int i = 0; i < dataBarang.length; i++) {
            String kode_detail = uniqid.get();
            String kode_barang = dataBarang[i][0];
            String qty = dataBarang[i][1];
            String[][] dataDtlTrMasuk = {
                {"kode_detail", kode_detail},
                {"kode_transaksi", kode_transaksi},
                {"kode_barang", kode_barang},
                {"qty", qty}
            };
            keluar.save_detail(dataDtlTrMasuk);

            String[] data_petugas = petugas.get_id(kode_petugas);
            kode_gudang = data_petugas[5];
            String[] data_stok = stok.getStok(kode_barang, kode_gudang);
            if (data_stok == null) {
                String kode_stok = uniqid.get();
                String[][] data = {
                    {"kode_stok", kode_stok},
                    {"kode_barang", kode_barang},
                    {"stok", qty},
                    {"kode_gudang", kode_gudang}
                };
                stok.save(data);
            }else{
                String kode_stok = data_stok[0];
                int stokAwal = Integer.parseInt(data_stok[2]);
                int stokKeluar = Integer.parseInt(qty);
                int stokSekarang = stokAwal - stokKeluar;
                String[][] data = {
                    {"kode_barang", kode_barang},
                    {"stok", String.valueOf(stokSekarang)},
                    {"kode_gudang", kode_gudang}
                };
                stok.edit(data, kode_stok);
            }
        }
        this.setVisible(false);
        mu.clearTransaksiKeluarCabang();
        mu.clearTbSementara(mu.modelTbSementaraTransaksiKeluarCabang);
        mu.showPanelTengah(mu.panelTransaksiKeluarCabang, "transaksi keluar cabang");
    }//GEN-LAST:event_btnTambahTranaksiKeluarCabangActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluarCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluarCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluarCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluarCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                modalPilihTransaksiKeluarCabang dialog = new modalPilihTransaksiKeluarCabang(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahTranaksiKeluarCabang;
    private javax.swing.JComboBox cbbNamaGudang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtKodeGudang;
    // End of variables declaration//GEN-END:variables
}
