/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author imam
 */
public class modalPilihTransaksiKeluar extends javax.swing.JDialog {
    MenuUtama mu;
    String[] session;
    /**
     * Creates new form modalPilihTransaksiKeluar
     */
    public modalPilihTransaksiKeluar(java.awt.Frame parent, boolean modal, String[] dataSession, MenuUtama mu) {
        super(parent, modal);
        initComponents();
        this.mu= mu;
        session = dataSession;
        jLabel1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTransaksiKeluarPengecer = new javax.swing.JButton();
        btnTransaksiKeluarCabang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(220, 239, 201));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Pilih Transaksi Keluar");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 204, 30));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        btnTransaksiKeluarPengecer.setBackground(new java.awt.Color(0, 102, 102));
        btnTransaksiKeluarPengecer.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTransaksiKeluarPengecer.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksiKeluarPengecer.setText("Pengecer");
        btnTransaksiKeluarPengecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksiKeluarPengecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiKeluarPengecerActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksiKeluarPengecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        btnTransaksiKeluarCabang.setBackground(new java.awt.Color(0, 102, 102));
        btnTransaksiKeluarCabang.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTransaksiKeluarCabang.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksiKeluarCabang.setText("Cabang");
        btnTransaksiKeluarCabang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksiKeluarCabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiKeluarCabangActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksiKeluarCabang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnTransaksiKeluarPengecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiKeluarPengecerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mu.clearTransaksiKeluarPengecer();
        mu.showPanelTengah(mu.panelTransaksiKeluarPengecer, "transaksi keluar pengecer");
    }//GEN-LAST:event_btnTransaksiKeluarPengecerActionPerformed

    private void btnTransaksiKeluarCabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiKeluarCabangActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mu.showPanelTengah(mu.panelTransaksiKeluarCabang, "transaksi keluar cabang");
    }//GEN-LAST:event_btnTransaksiKeluarCabangActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(modalPilihTransaksiKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                modalPilihTransaksiKeluar dialog = new modalPilihTransaksiKeluar(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransaksiKeluarCabang;
    private javax.swing.JButton btnTransaksiKeluarPengecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
